name : workflow with events
on :
 push:
  branches:
    - main
jobs: 
     first-job:
           runs-on: ubuntu-latest
           steps:
               - name: step one
                 run:  echo "step one"
